package com.woojin.paymanagement.strings

/**
 * English language implementation of AppStrings
 */
object EnglishStrings : AppStrings {
    // ===== Common =====
    override val appName = "Pay Management"
    override val confirm = "Confirm"
    override val cancel = "Cancel"
    override val save = "Save"
    override val delete = "Delete"
    override val edit = "Edit"
    override val close = "Close"
    override val back = "Back"
    override val next = "Next"
    override val done = "Done"
    override val start = "Start"
    override val settings = "Settings"
    override val notice = "Notice"
    override val warning = "Warning"
    override val error = "Error"
    override val success = "Success"
    override val loading = "Loading..."
    override val empty = "Empty"
    override val all = "All"
    override val none = "None"
    override val add = "Add"
    override val search = "Search"
    override val reset = "Reset"
    override val apply = "Apply"
    override val select = "Select"
    override val change = "Change"
    override val manage = "Manage"
    override val fold = "Collapse"
    override val expand = "Expand"

    // ===== Numbers & Currency =====
    override val currencySymbol = "₩"
    override fun amountWithUnit(amount: String) = "₩$amount"
    override fun won(amount: Long) = "₩$amount"
    override fun percentage(value: Int) = "$value%"
    override fun dayOfMonth(day: Int) = "${day}${getDaySuffix(day)}"

    private fun getDaySuffix(day: Int): String = when {
        day in 11..13 -> "th"
        day % 10 == 1 -> "st"
        day % 10 == 2 -> "nd"
        day % 10 == 3 -> "rd"
        else -> "th"
    }

    // ===== Date & Time =====
    override fun monthYear(year: Int, month: Int) = "${getMonthName(month)} $year"
    override fun fullDate(year: Int, month: Int, day: Int) = "${getMonthName(month)} ${day}${getDaySuffix(day)}, $year"
    override fun shortDate(month: Int, day: Int) = "${getMonthNameShort(month)} ${day}${getDaySuffix(day)}"
    override fun dayWithWeekday(day: Int, weekday: String) = "$weekday, ${day}${getDaySuffix(day)}"

    private fun getMonthName(month: Int): String = when (month) {
        1 -> "January"
        2 -> "February"
        3 -> "March"
        4 -> "April"
        5 -> "May"
        6 -> "June"
        7 -> "July"
        8 -> "August"
        9 -> "September"
        10 -> "October"
        11 -> "November"
        12 -> "December"
        else -> ""
    }

    private fun getMonthNameShort(month: Int): String = when (month) {
        1 -> "Jan"
        2 -> "Feb"
        3 -> "Mar"
        4 -> "Apr"
        5 -> "May"
        6 -> "Jun"
        7 -> "Jul"
        8 -> "Aug"
        9 -> "Sep"
        10 -> "Oct"
        11 -> "Nov"
        12 -> "Dec"
        else -> ""
    }

    override val sunday = "Sunday"
    override val monday = "Monday"
    override val tuesday = "Tuesday"
    override val wednesday = "Wednesday"
    override val thursday = "Thursday"
    override val friday = "Friday"
    override val saturday = "Saturday"
    override fun weekdayShort(weekday: String) = when (weekday) {
        "Sunday" -> "Sun"
        "Monday" -> "Mon"
        "Tuesday" -> "Tue"
        "Wednesday" -> "Wed"
        "Thursday" -> "Thu"
        "Friday" -> "Fri"
        "Saturday" -> "Sat"
        else -> weekday.take(3)
    }
    override val today = "Today"
    override val yesterday = "Yesterday"
    override val tomorrow = "Tomorrow"

    // ===== Transaction Types =====
    override val income = "Income"
    override val expense = "Expense"
    override val transfer = "Transfer"
    override val saving = "Savings"
    override val transactionType = "Transaction Type"

    // ===== Categories =====
    override val category = "Category"
    override val categoryManagement = "Category Management"
    override val addIncomeCategory = "Add Income Category"
    override val addExpenseCategory = "Add Expense Category"
    override val addCategory = "Add Category"
    override val deleteCategory = "Delete Category"
    override val editCategory = "Edit Category"
    override val incomeCategories = "Income Categories"
    override val expenseCategories = "Expense Categories"
    override val categoryName = "Category Name"
    override val selectCategory = "Select Category"
    override val noCategorySelected = "No category selected"
    override val uncategorized = "Uncategorized"
    override val categoryColor = "Category Color"
    override val categoryIcon = "Category Icon"
    override val defaultCategories = "Default Categories"
    override val customCategories = "Custom Categories"
    override val cannotDeleteDefaultCategory = "Cannot delete default category"
    override val categoryInUseCannotDelete = "Cannot delete category in use"
    override val deleteCategoryConfirm = "Delete this category?"

    // Default category names
    override val categorySalary = "Salary"
    override val categoryBonus = "Bonus"
    override val categoryInvestment = "Investment"
    override val categoryAllowance = "Allowance"
    override val categoryOtherIncome = "Other Income"
    override val categoryFood = "Food"
    override val categoryTransport = "Transport"
    override val categoryShopping = "Shopping"
    override val categoryEntertainment = "Entertainment"
    override val categoryHealth = "Health"
    override val categoryEducation = "Education"
    override val categoryHousing = "Housing"
    override val categoryTelecom = "Telecom"
    override val categoryOtherExpense = "Other Expense"

    // ===== Payday Setup =====
    override val paydaySetup = "Payday Setup"
    override val paydaySetupTitle = "Set Your Payday"
    override val paydaySetupSubtitle = "Track your spending by pay period"
    override val paydaySetupDescription = "Track your spending by pay period"
    override val selectPaydayPrompt = "Please select your payday"
    override val paydayOnWeekendHoliday = "If payday falls on a weekend/holiday"
    override val payBeforeWeekday = "Pay on previous weekday"
    override val payAfterWeekday = "Pay on next weekday"
    override val setupComplete = "Complete Setup"
    override val selectPayday = "Select Payday"
    override val paydayChange = "Change Payday"
    override val currentPayday = "Current Payday"
    override val paydayAdjustment = "Weekend/Holiday Adjustment"
    override val beforeWeekend = "Pay before weekend"
    override val afterWeekend = "Pay after weekend"
    override val beforeWeekendDesc = "Pay on previous business day if weekend/holiday"
    override val afterWeekendDesc = "Pay on next business day if weekend/holiday"
    override val monthlySalary = "Monthly Salary"
    override val enterSalary = "Enter your salary"
    override val salaryOptional = "Optional"
    override val confirmPayday = "Confirm"
    override val paydayChangeConfirm = "Change payday?"
    override val paydayChangeDesc = "Go to payday settings."
    override val goToPaydaySettings = "Change"
    override val welcomeMessage = "Welcome!"
    override val welcomeSubMessage = "Start managing your pay"
    override fun paydayDisplay(day: Int) = "${day}${getDaySuffix(day)}"

    // ===== Calendar Screen =====
    override val payPeriodSummary = "Pay Period Summary"
    override val remainingBudget = "Remaining Budget"
    override val totalIncome = "Total Income"
    override val totalExpense = "Total Expense"
    override val balance = "Balance"
    override val dailyAverage = "Daily Average"
    override val remainingDays = "Days Left"
    override val noTransactions = "No transactions"
    override val addFirstTransaction = "Add your first transaction"
    override val viewTransactions = "View Transactions"
    override val tapToAddTransaction = "Tap to add transaction"
    override fun remainingDaysCount(days: Int) = "$days days left"
    override fun daysRemaining(days: Int) = "$days days"
    override fun dailyBudgetRecommend(amount: String) = "Spend ₩$amount/day recommended"
    override val budgetExceeded = "Budget Exceeded"
    override val withinBudget = "Within Budget"
    override val showPayPeriod = "Show Pay Period"
    override val hidePayPeriod = "Hide Pay Period"
    override val viewDetails = "View Details"
    override val payPeriodStart = "Period Start"
    override val payPeriodEnd = "Period End"
    override fun payPeriodRange(startMonth: Int, startDay: Int, endMonth: Int, endDay: Int) =
        "${getMonthNameShort(startMonth)} ${startDay}${getDaySuffix(startDay)} - ${getMonthNameShort(endMonth)} ${endDay}${getDaySuffix(endDay)}"
    override val incomeExpenseRatio = "Income/Expense Ratio"
    override val spendingPace = "Spending Pace"
    override val onTrack = "On Track"
    override val overSpending = "Over Spending"
    override val underSpending = "Under Spending"
    override val weekdaysShort = listOf("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
    override val selectDateToMove = "Select a date to move to"
    override val selectDateToViewMemo = "Select a date to view details"
    override val tapCalendarToViewMemo = "Tap a date on the calendar to view transactions"
    override val cardPaymentHistory = "Card Payments"
    override val parsingPermission = "Parsing"
    override val pushPermission = "Push"
    override val yearLabel = "Year"
    override val monthLabel = "Month"
    override fun yearDisplay(year: Int) = "$year"
    override fun monthDisplayShort(month: Int) = getMonthNameShort(month)
    override val previousYear = "Previous year"
    override val nextYear = "Next year"
    override val previousMonthLabel = "Previous month"
    override val nextMonthLabel = "Next month"
    override fun dateTransactionHeader(month: Int, day: Int) = "${getMonthNameShort(month)} ${day}${getDaySuffix(day)} Transactions"
    override val noTransactionsOnDate = "No transactions on this date"

    // ===== Add/Edit Transaction =====
    override val addTransaction = "Add Transaction"
    override val editTransaction = "Edit Transaction"
    override val transactionDate = "Date"
    override val transactionAmount = "Amount"
    override val transactionMemo = "Memo"
    override val enterAmount = "Enter amount"
    override val enterMemo = "Enter memo"
    override val selectDate = "Select Date"
    override val selectPaymentMethod = "Select Payment Method"
    override val cash = "Cash"
    override val card = "Card"
    override val bankTransfer = "Bank Transfer"
    override val giftCard = "Gift Card"
    override val paymentMethod = "Payment Method"
    override val transactionSaved = "Transaction saved"
    override val transactionDeleted = "Transaction deleted"
    override val deleteTransactionConfirm = "Delete this transaction?"
    override val amountRequired = "Please enter an amount"
    override val invalidAmount = "Please enter a valid amount"
    override val memo = "Memo"
    override val noMemo = "No memo"
    override val transactionDetails = "Transaction Details"
    override val duplicateTransaction = "Duplicate Transaction"
    override val similarTransactionExists = "A similar transaction already exists"

    // ===== Date Detail Screen =====
    override val dateDetail = "Date Details"
    override val transactionsForDay = "Transactions for the Day"
    override fun transactionCount(count: Int) = if (count == 1) "1 transaction" else "$count transactions"
    override val noTransactionsForDay = "No transactions for this day"
    override val dailySummary = "Daily Summary"
    override val totalForDay = "Daily Total"
    override val incomeForDay = "Daily Income"
    override val expenseForDay = "Daily Expense"
    override val deleteTransactionTitle = "Delete Transaction"
    override val cannotDeleteTransaction = "Cannot Delete Transaction"
    override val recurringShort = "Recurring"
    override val saveAsRecurring = "Save as recurring"
    override fun transactionListHeader(count: Int) = if (count == 1) "Transaction (1)" else "Transactions ($count)"

    // ===== Statistics Screen =====
    override val statistics = "Statistics"
    override val statisticsTitle = "Spending Analysis"
    override val monthlyStatistics = "Monthly Statistics"
    override val categoryStatistics = "Category Statistics"
    override val paymentMethodStatistics = "Payment Method Statistics"
    override val spendingTrend = "Spending Trend"
    override val incomeVsExpense = "Income vs Expense"
    override val topCategories = "Top Categories"
    override val topExpenseCategories = "Top Expense Categories"
    override val topIncomeCategories = "Top Income Categories"
    override val noDataForPeriod = "No data for this period"
    override val averageDaily = "Daily Avg"
    override val averageMonthly = "Monthly Avg"
    override val highestSpendingDay = "Highest Spending Day"
    override val lowestSpendingDay = "Lowest Spending Day"
    override val totalTransactions = "Total Transactions"
    override val chartView = "Chart View"
    override val listView = "List View"
    override val pieChart = "Pie Chart"
    override val barChart = "Bar Chart"
    override val lineChart = "Line Chart"
    override fun categoryPercentage(category: String, percentage: Int) = "$category $percentage%"

    // ===== Budget Settings =====
    override val budgetSettings = "Budget Settings"
    override val setBudget = "Set Budget"
    override val editBudget = "Edit Budget"
    override val deleteBudget = "Delete Budget"
    override val monthlyBudget = "Monthly Budget"
    override val categoryBudget = "Category Budget"
    override val budgetAmount = "Budget Amount"
    override val enterBudgetAmount = "Enter budget amount"
    override val budgetRemaining = "Remaining"
    override val budgetUsed = "Used"
    override val budgetExceededWarning = "Budget exceeded!"
    override val noBudgetSet = "No budget set"
    override val budgetSaved = "Budget saved"
    override val budgetDeleted = "Budget deleted"
    override val deleteBudgetConfirm = "Delete this budget?"
    override val viewBudgetProgress = "View Progress"
    override fun budgetProgress(used: String, total: String) = "₩$used / ₩$total"
    override fun budgetRemainingAmount(amount: String) = "₩$amount remaining"
    override fun budgetExceededAmount(amount: String) = "₩$amount over"
    override val budgetExceededNotification = "Budget Exceeded"
    override val totalBudget = "Total Budget"
    override val usedAmount = "Used Amount"
    override val remainingAmount = "Remaining"
    override val budgetUtilization = "Budget Utilization"

    // ===== Card Management =====
    override val cardManagement = "Card Management"
    override val addCard = "Add Card"
    override val editCard = "Edit Card"
    override val deleteCard = "Delete Card"
    override val cardName = "Card Name"
    override val cardType = "Card Type"
    override val creditCard = "Credit Card"
    override val debitCard = "Debit Card"
    override val prepaidCard = "Prepaid Card"
    override val balanceCard = "Balance Card"
    override val cardBalance = "Card Balance"
    override val enterCardName = "Enter card name"
    override val enterCardBalance = "Enter balance"
    override val cardList = "Card List"
    override val noCards = "No cards registered"
    override val addFirstCard = "Add your first card"
    override val cardSaved = "Card saved"
    override val cardDeleted = "Card deleted"
    override val deleteCardConfirm = "Delete this card?"
    override val cardDetails = "Card Details"
    override val lastUsed = "Last Used"
    override val totalSpent = "Total Spent"
    override val balanceCardManagement = "Balance Card Management"
    override val giftCardManagement = "Gift Card Management"
    override val addBalanceCard = "Add Balance Card"
    override val addGiftCard = "Add Gift Card"
    override val editBalanceCard = "Edit Balance Card"
    override val editGiftCard = "Edit Gift Card"
    override val initialBalance = "Initial Balance"
    override val currentBalance = "Current Balance"
    override val usedBalance = "Used Balance"
    override val expirationDate = "Expiration Date"
    override val noExpirationDate = "No expiration date"
    override val setExpirationDate = "Set Expiration Date"
    override val cardExpired = "Expired"
    override val cardExpiringSoon = "Expiring Soon"
    override val activeCards = "Active Cards"
    override val inactiveCards = "Inactive Cards"
    override val markAsUsed = "Mark as Used"
    override val activateCard = "Activate Card"

    // ===== Recurring Transactions =====
    override val recurringTransactions = "Recurring Transactions"
    override val addRecurringTransaction = "Add Recurring"
    override val editRecurringTransaction = "Edit Recurring"
    override val deleteRecurringTransaction = "Delete Recurring"
    override val recurringTransactionName = "Transaction Name"
    override val recurrencePattern = "Recurrence"
    override val daily = "Daily"
    override val weekly = "Weekly"
    override val monthly = "Monthly"
    override val yearly = "Yearly"
    override val everyDay = "Every Day"
    override val everyWeek = "Every Week"
    override val everyMonth = "Every Month"
    override val everyYear = "Every Year"
    override val selectRecurrenceDay = "Select Day"
    override val recurringAmount = "Amount"
    override val startDate = "Start Date"
    override val endDate = "End Date"
    override val noEndDate = "No End Date"
    override val nextOccurrence = "Next Occurrence"
    override val lastExecuted = "Last Executed"
    override val neverExecuted = "Never Executed"
    override val recurringTransactionSaved = "Recurring transaction saved"
    override val recurringTransactionDeleted = "Recurring transaction deleted"
    override val deleteRecurringTransactionConfirm = "Delete this recurring transaction?"
    override val recurringTransactionPaused = "Recurring transaction paused"
    override val recurringTransactionResumed = "Recurring transaction resumed"
    override val pauseRecurring = "Pause"
    override val resumeRecurring = "Resume"
    override val executeNow = "Execute Now"
    override val skipNext = "Skip Next"
    override val noRecurringTransactions = "No recurring transactions"
    override val addFirstRecurringTransaction = "Add your first recurring transaction"
    override val recurringTransactionDetails = "Recurring Details"
    override val autoAdd = "Auto Add"
    override val manualConfirm = "Manual Confirm"
    override val autoAddDesc = "Automatically adds on the scheduled date"
    override val manualConfirmDesc = "Confirm via notification before adding"
    override fun recurringDayOfMonth(day: Int) = "Every ${day}${getDaySuffix(day)}"
    override fun recurringDayOfWeek(weekday: String) = "Every $weekday"
    override val todaysRecurringTransactions = "Today's Recurring"
    override val pendingRecurringTransactions = "Pending"

    // ===== Parsed Transactions (SMS/Notification) =====
    override val parsedTransactions = "Parsed Transactions"
    override val cardNotificationParsing = "Card Notification Parsing"
    override val parsedTransactionsList = "Parsed Transactions"
    override val addToParsed = "Add"
    override val ignoreParsed = "Ignore"
    override val allParsed = "All"
    override val parsedFromNotification = "Parsed from notification"
    override val noParsedTransactions = "No parsed transactions"
    override val parsedTransactionAdded = "Transaction added"
    override val parsedTransactionIgnored = "Transaction ignored"
    override val deleteAllParsed = "Delete All"
    override val deleteAllParsedConfirm = "Delete all parsed transactions?"
    override val cardNotificationDetection = "Card Notification Detection"
    override val cardNotificationDetectionDesc = "Parse card notifications from other apps"
    override val appNotification = "App Notification"
    override val appNotificationDesc = "Receive notifications from the app"

    // ===== Theme Settings =====
    override val themeSettings = "Theme Settings"
    override val theme = "Theme"
    override val lightTheme = "Light Mode"
    override val darkTheme = "Dark Mode"
    override val systemTheme = "System Default"
    override val themeLight = "Light"
    override val themeDark = "Dark"
    override val themeSystem = "System"

    // ===== Language Settings =====
    override val languageSettings = "Language Settings"
    override val language = "Language"
    override val korean = "한국어"
    override val english = "English"
    override val languageChangeRestart = "Restart the app to apply language changes"
    override val selectLanguage = "Select Language"

    // ===== Data Management =====
    override val dataManagement = "Data Management"
    override val exportData = "Export Data"
    override val importData = "Import Data"
    override val exportToJson = "Export to JSON"
    override val importFromJson = "Import from JSON"
    override val exportDataDesc = "Save all data to a JSON file"
    override val importDataDesc = "Restore data from a JSON file"
    override val exportSuccess = "Data exported successfully"
    override val exportFailed = "Export failed"
    override val importSuccess = "Data imported successfully"
    override val importFailed = "Import failed"
    override val importConfirm = "Import Data"
    override val importConfirmDesc = "Import data from the JSON file.\nExisting data will be deleted.\n\nContinue?"
    override val importWarning = "Warning"
    override val existingDataWillBeDeleted = "Existing data will be deleted"
    override val fileLoadFailed = "Failed to load file"
    override fun importResult(success: Int, failed: Int) = "Import complete\nSuccess: $success, Failed: $failed"
    override val backupData = "Backup Data"
    override val restoreData = "Restore Data"

    // ===== Calculator =====
    override val calculator = "Calculator"
    override val calculate = "Calculate"
    override val clear = "Clear"
    override val clearAll = "Clear All"
    override val equals = "="
    override val useResult = "Use Result"
    override val calculatorResult = "Result"

    // ===== Tip Donation =====
    override val tipDonation = "Support Developer"
    override val tipDonationTitle = "Support Developer"
    override val tipDonationDesc = "Help support app development"
    override val supportDeveloper = "Support Developer"
    override val smallTip = "Coffee"
    override val mediumTip = "Lunch"
    override val largeTip = "Dinner"
    override val thankYouForTip = "Thank you for your support!"
    override val tipPurchaseFailed = "Purchase failed"
    override val tipAlreadyPurchased = "Already purchased"

    // ===== Ad Removal =====
    override val adRemoval = "Remove Ads"
    override val removeAds = "Remove Ads"
    override val adRemovalDesc = "Use the app without ads"
    override val adRemovalBenefit = "Ad Removal Benefits"
    override val adFreeExperience = "Ad-free experience"
    override val purchaseAdRemoval = "Purchase Ad Removal"
    override val adRemovalActive = "Ad removal active"
    override val adRemovalExpired = "Ad removal expired"
    override fun adRemovalExpiresIn(days: Int) = "Expires in $days days"
    override val restorePurchase = "Restore Purchase"
    override val purchaseFailed = "Purchase failed"
    override val purchaseSuccess = "Purchase successful"

    // ===== Coupon =====
    override val coupon = "Coupon"
    override val enterCoupon = "Enter Coupon"
    override val couponCode = "Coupon Code"
    override val applyCoupon = "Apply Coupon"
    override val invalidCoupon = "Invalid coupon"
    override val couponAlreadyUsed = "Coupon already used"
    override val couponApplied = "Coupon applied"
    override val couponExpired = "Coupon expired"
    override val couponNotFound = "Coupon not found"
    override val enterCouponCode = "Enter coupon code"

    // ===== Monthly Comparison =====
    override val monthlyComparison = "Monthly Comparison"
    override val compareMonths = "Compare Months"
    override val previousMonth = "Previous Month"
    override val currentMonth = "Current Month"
    override val difference = "Difference"
    override val increased = "Increased"
    override val decreased = "Decreased"
    override val noChange = "No Change"
    override fun comparedToLastMonth(amount: String) = "₩$amount vs last month"
    override fun increasePercentage(percentage: Int) = "$percentage% increase"
    override fun decreasePercentage(percentage: Int) = "$percentage% decrease"
    override val previousPayPeriod = "Previous Pay Period"
    override val currentPayPeriod = "Current Pay Period"
    override val payPeriodComparison = "Pay Period Comparison"
    override val newPayPeriodStarted = "New pay period started! Compare with last period"
    override val compareWithPreviousPeriod = "Compare with previous period"

    // ===== Tutorial =====
    override val tutorialWelcome = "Welcome!"
    override val tutorialCalendar = "View daily transactions on the calendar"
    override val tutorialAddTransaction = "Tap here to add a transaction"
    override val tutorialStatistics = "Analyze your spending patterns"
    override val tutorialBudget = "Set budgets and manage spending"
    override val tutorialSkip = "Skip"
    override val tutorialNext = "Next"
    override val tutorialFinish = "Finish"
    override val tutorialDontShowAgain = "Don't show again"
    override val tapHereToAdd = "Tap here to add"
    override val swipeToNavigate = "Swipe to navigate"
    override val longPressForOptions = "Long press for options"

    // ===== Permissions =====
    override val permissionRequired = "Permission Required"
    override val notificationListenerPermission = "Notification Listener Permission"
    override val notificationListenerPermissionDesc = "Notification listener permission is required to detect card notifications.\n\nGo to settings?"
    override val postNotificationPermission = "Post Notification Permission"
    override val postNotificationPermissionDesc = "Notification permission is required to show app notifications.\n\nGo to settings?"
    override val goToSettings = "Go to Settings"
    override val permissionDenied = "Permission denied"
    override val permissionGranted = "Permission granted"

    // ===== Errors & Validation =====
    override val networkError = "Network error"
    override val unknownError = "Unknown error"
    override val tryAgain = "Try Again"
    override val dataLoadFailed = "Failed to load data"
    override val dataSaveFailed = "Failed to save data"
    override val requiredField = "This field is required"
    override val invalidInput = "Invalid input"
    override val valueTooLarge = "Value is too large"
    override val valueTooSmall = "Value is too small"
    override val pleaseEnterValidAmount = "Please enter a valid amount"
    override val pleaseSelectCategory = "Please select a category"
    override val connectionFailed = "Connection failed"
    override val timeout = "Timeout"

    // ===== Drawer Menu =====
    override val pushNotifications = "Push Notifications"
    override val aboutApp = "About"
    override val version = "Version"
    override val contactSupport = "Contact Support"
    override val rateApp = "Rate App"
    override val privacyPolicy = "Privacy Policy"
    override val termsOfService = "Terms of Service"
    override val appExit = "Exit App"
    override val exitConfirm = "Exit"
    override val exitConfirmMessage = "Exit the app?"
    override val hideMoneyAmounts = "Hide Amounts"
    override val showMoneyAmounts = "Show Amounts"
    override val moneyVisibility = "Amount Visibility"
    override fun addIncomeExpenseCategory(type: String) = "Add or delete $type categories"

    // ===== Snackbar & Toast Messages =====
    override val changesSaved = "Changes saved"
    override val changesDiscarded = "Changes discarded"
    override val operationSuccess = "Operation successful"
    override val operationFailed = "Operation failed"
    override val copiedToClipboard = "Copied to clipboard"
    override val undoAction = "Undo"
    override val actionCancelled = "Action cancelled"

    // ===== Empty States =====
    override val noDataYet = "No data yet"
    override val startByAdding = "Start by adding"
    override val nothingToShow = "Nothing to show"
    override val emptyCategory = "No categories"
    override val emptyCardList = "No cards registered"
    override val emptyTransactionList = "No transactions"
    override val emptyBudgetList = "No budgets set"
    override val emptyRecurringList = "No recurring transactions"
    override val emptyStatistics = "No statistics data"

    // ===== Accessibility =====
    override val closeDialog = "Close dialog"
    override val openMenu = "Open menu"
    override val closeMenu = "Close menu"
    override val goBack = "Go back"
    override val moreOptions = "More options"
    override val refresh = "Refresh"
    override val scrollUp = "Scroll up"
    override val scrollDown = "Scroll down"
    override val expandSection = "Expand section"
    override val collapseSection = "Collapse section"

    // ===== Statistics (additional) =====
    override val incomeAnalysis = "Income Analysis"
    override val expenseAnalysis = "Expense Analysis"
    override val investmentActivityAnalysis = "Investment Activity Analysis"
    override val savingActivitySummary = "Savings Activity Summary"
    override val savingCategories = "Savings Categories"
    override val addSavingCategory = "Add Savings Category"
    override val investmentActivitySummary = "Investment Activity Summary"
    override val investment = "Investment"
    override val stopLoss = "Stop Loss"
    override val profitTaking = "Profit Taking"
    override val dividend = "Dividend"
    override val paymentMethodAnalysis = "Payment Method Analysis"
    override val noTransactionsForPeriod = "No transactions for this period"
    override val differenceAmount = "Difference"
    override val charge = "Charge"
    override val usage = "Usage"
    override val purchase = "Purchase"
    override val settlementIncome = "Settlement Income"
    override val actualUsage = "Actual Usage"
    override val other = "Other"

    // ===== Budget (additional) =====
    override val budgetManagement = "Budget Management"
    override val usageStatus = "Usage Status"
    override val overallProgress = "Overall Progress"
    override val spendingPlan = "Spending Plan"
    override val plannedTotal = "Planned Total:"
    override val salaryLabel = "Salary:"
    override val budgetLabel = "Budget:"
    override val usedLabel = "Used:"
    override val remainingLabel = "Remaining:"
    override val exceededLabel = "Exceeded:"
    override val noBudgetCategoriesMessage = "No budget categories set.\nAdd categories in the \"Budget Settings\" tab."
    override val addCategoryLabel = "+ Add Category"
    override val allocatedAmount = "Allocated Amount"
    override val enterAmountPlaceholder = "Enter amount"
    override val selectCategoriesMultiple = "Select Categories (multiple allowed)"
    override val groupNameInput = "Enter Group Name"
    override val groupNameLabel = "Group Name"
    override val memoOptional = "Memo (optional)"
    override val noCategoriesAvailable = "No categories available to add."
    override val includedCategories = "Included Categories:"
    override val categorySpending = "Spending by Category:"
    override val totalLabel = "Total:"
    override val editSalary = "Edit Salary"
    override val setSalary = "Set your salary"
    override val addCategoryBudget = "Add Category Budget"
    override fun editBudgetTitle(emoji: String, name: String) = "$emoji $name Budget Edit"

    // ===== Add Transaction (additional) =====
    override val savingTransaction = "Saving..."
    override val dateLabel = "Date"
    override val merchantLabel = "Merchant"
    override val incomeType = "Income Type"
    override val newBalanceCard = "Add New Balance Card"
    override val chargeExistingBalanceCard = "Charge Existing Balance Card"
    override val balanceCardNameHint = "Balance card name (e.g., Store voucher)"
    override val giftCardNameHint = "Gift card name (e.g., Department store)"
    override val selectBalanceCardToCharge = "Select balance card to charge"
    override val selectBalanceCardLabel = "Select Balance Card"
    override val selectGiftCardLabel = "Select Gift Card"
    override val dutchPaySettlement = "Dutch Pay / Settlement"
    override val settlementAmountLabel = "Settlement Amount"
    override val settlementDescription = "Your actual amount is the payment minus the settlement amount"
    override fun balanceCardFullUsage(amount: Int, remaining: Int) = "Balance card ₩$amount used, ₩$remaining remaining"
    override fun balanceCardPartialUsage(cardAmount: Int, cashAmount: Int) = "Balance card ₩$cardAmount + Cash ₩$cashAmount"
    override fun giftCardFullUsage(amount: Int) = "Gift card ₩$amount fully used"
    override fun giftCardRefundUsage(amount: Int, refund: Int) = "Gift card ₩$amount used, ₩$refund cash refund"
    override fun giftCardPartialUsage(cardAmount: Int, cashAmount: Int) = "Gift card ₩$cardAmount + Cash ₩$cashAmount"

    // ===== Calculator (additional) =====
    override val periodCalculator = "Period Calculator"
    override val periodSetting = "Period Setting"
    override val editPeriod = "Edit Period"
    override val totalAmount = "Total"
    override val transactionCountLabel = "Transactions"
    override val averageAmount = "Average"
    override val selectStartDate = "Select start date"
    override val selectEndDate = "Select end date"
    override val selectionComplete = "Selection complete"
    override val transactionDetail = "Transaction Details"

    // ===== Theme (additional) =====
    override val systemThemeDesc = "Follows your device theme settings"

    // ===== Coupon (additional) =====
    override val couponCodeInput = "Enter Coupon Code"
    override val couponDesc = "Enter a coupon code to enjoy 3 days of ad-free experience."
    override val applyingCoupon = "Applying..."
    override val applyCouponButton = "Apply Coupon"
    override val couponApplyComplete = "Coupon Applied!"
    override val couponSuccessMessage = "Coupon applied successfully.\nEnjoy 3 days of ad-free experience.\n\nRestart the app to apply."

    // ===== Ad Removal (additional) =====
    override val useWithoutAds = "Use Without Ads"
    override val adRemovalLongDesc = "Enjoy an ad-free experience!\nSelect a period and ads will be removed for that duration."
    override val oneDayPass = "1-Day Pass"
    override val threeDayPass = "3-Day Pass"
    override val sevenDayPass = "7-Day Pass"
    override val thirtyDayPass = "30-Day Pass"
    override val processingPayment = "Processing..."
    override fun payAmountButton(amount: String) = "Pay ₩$amount"
    override val selectPeriod = "Select a period"
    override val purchaseComplete = "Purchase Complete!"
    override val adRemovalCompleteMessage = "Ad removal complete.\nEnjoy the app ad-free!"
    override val paymentFailedTitle = "Payment Failed"

    // ===== Tip Donation (additional) =====
    override val tipDonationScreenTitle = "Tip"
    override val supportDeveloperTitle = "Support the Developer"
    override val tipDonationLongDesc = "Is the app helpful?\nBuy the developer a coffee!"
    override val buyCoffee = "Buy a Coffee"
    override val buyLunch = "Buy Lunch"
    override val buyDinner = "Buy Dinner"
    override val selectAmountPrompt = "Please select an amount"
    override val thankYouTitle = "Thank you!"
    override val thankYouMessage = "Thank you for supporting the developer.\nWe'll make an even better app!"

    // ===== Monthly Comparison (additional) =====
    override val categoryComparison = "Category Comparison"
    override val noComparisonData = "No data to compare"
    override val totalExpenseComparison = "📊 Total Expense Comparison"
    override val previous = "Previous"
    override val current = "Current"
    override val increasedArrow = "Increased ↑"
    override val savingsArrow = "Savings ↓"
    override val same = "Same"

    // ===== Parsed Transactions (additional) =====
    override val parsedTransactionDesc = "Transactions parsed from notifications. Tap an item to add it as a transaction."
    override fun errorWithMessage(message: String) = "Error: $message"
    override val cardNotificationAutoDisplay = "Card payment notifications will appear here automatically"
    override val notificationOn = "🔔 Alerts"
    override val notificationOff = "🔕 Alerts"

    // ===== Category Management (additional) =====
    override val emojiLabel = "Emoji"
    override val continueAction = "Continue"
    override fun deleteCategoryConfirmMessage(emoji: String, name: String) = "Are you sure you want to delete the $emoji $name category?"

    // ===== Card Management (additional) =====
    override val balanceGiftCardManagement = "Balance/Gift Card Management"
    override val activeTab = "Active"
    override val completedTab = "Used Up"
    override val noActiveCards = "No active cards"
    override val noCompletedCards = "No used up cards"
    override fun balanceDisplay(amount: String) = "Balance: ₩$amount"
    override val transactionHistory = "Transaction History"
    override val noTransactionHistory = "No transaction history"
    override fun incomeAmountDisplay(amount: String) = "+₩$amount"
    override fun expenseAmountDisplay(amount: String) = "-₩$amount"

    // ===== Recurring Transaction (additional) =====
    override val recurringTransactionManagement = "Recurring Transactions"
    override val todayItems = "Today's Items"
    override val noRegisteredRecurringTransactions = "No recurring transactions"
    override fun paymentMethodDisplay(method: String) = "Payment: $method"
    override val cashCheckCard = "Cash/Debit Card"
    override val recurringPatternLabel = "Recurrence Pattern"
    override val whichDayOfMonth = "Which day of the month?"
    override val whichDayOfWeek = "Which day of the week?"
    override val weekendHandling = "Weekend Handling"
    override val applyAsIs = "Keep as is"
    override val moveToPreviousWeekday = "Move to previous weekday"
    override val moveToNextWeekday = "Move to next weekday"
    override val noCategoriesRegistered = "No categories registered"
    override val memoOptionalShort = "Memo (optional)"

    // ===== Custom Payment Method Management =====
    override val paymentMethodManagement = "Payment Methods"
    override val addPaymentMethod = "Add Payment Method"
    override val editPaymentMethod = "Edit Payment Method"
    override val deletePaymentMethod = "Delete Payment Method"
    override val paymentMethodName = "Payment Method Name"
    override val paymentMethodManagementDesc = "Manage cards to track spending by card"
    override val defaultPaymentMethods = "Default Methods"
    override val customPaymentMethods = "Registered Cards"
    override val unspecifiedCard = "Unspecified"
    override fun deletePaymentMethodConfirmMessage(name: String) = "Are you sure you want to delete $name?"
    override fun totalPaymentMethodCount(defaultCount: Int, customCount: Int) = "${defaultCount + customCount} payment methods total"
    override fun defaultPaymentMethodCount(count: Int) = "$count"
    override fun customPaymentMethodCount(count: Int) = "$count"
    override val selectCard = "Select Card"
    override val defaultCard = "Default"
    override val setAsDefaultCard = "Set as Default"
    override val cardBreakdown = "Card Breakdown"
    override val transactionTools = "Transaction Tools"
}
