package com.woojin.paymanagement.strings

/**
 * Korean language implementation of AppStrings
 */
object KoreanStrings : AppStrings {
    // ===== Common =====
    override val appName = "월급 관리"
    override val confirm = "확인"
    override val cancel = "취소"
    override val save = "저장"
    override val delete = "삭제"
    override val edit = "수정"
    override val close = "닫기"
    override val back = "뒤로"
    override val next = "다음"
    override val done = "완료"
    override val start = "시작"
    override val settings = "설정"
    override val notice = "알림"
    override val warning = "경고"
    override val error = "오류"
    override val success = "성공"
    override val loading = "로딩 중..."
    override val empty = "비어 있음"
    override val all = "전체"
    override val none = "없음"
    override val add = "추가"
    override val search = "검색"
    override val reset = "초기화"
    override val apply = "적용"
    override val select = "선택"
    override val change = "변경"
    override val manage = "관리"
    override val fold = "접기"
    override val expand = "펼치기"

    // ===== Numbers & Currency =====
    override val currencySymbol = "원"
    override fun amountWithUnit(amount: String) = "${amount}원"
    override fun won(amount: Long) = "${amount}원"
    override fun percentage(value: Int) = "${value}%"
    override fun dayOfMonth(day: Int) = "${day}일"

    // ===== Date & Time =====
    override fun monthYear(year: Int, month: Int) = "${year}년 ${month}월"
    override fun fullDate(year: Int, month: Int, day: Int) = "${year}년 ${month}월 ${day}일"
    override fun shortDate(month: Int, day: Int) = "${month}월 ${day}일"
    override fun dayWithWeekday(day: Int, weekday: String) = "${day}일 (${weekday})"
    override val sunday = "일요일"
    override val monday = "월요일"
    override val tuesday = "화요일"
    override val wednesday = "수요일"
    override val thursday = "목요일"
    override val friday = "금요일"
    override val saturday = "토요일"
    override fun weekdayShort(weekday: String) = when (weekday) {
        "일요일" -> "일"
        "월요일" -> "월"
        "화요일" -> "화"
        "수요일" -> "수"
        "목요일" -> "목"
        "금요일" -> "금"
        "토요일" -> "토"
        else -> weekday.take(1)
    }
    override val today = "오늘"
    override val yesterday = "어제"
    override val tomorrow = "내일"

    // ===== Transaction Types =====
    override val income = "수입"
    override val expense = "지출"
    override val transfer = "이체"
    override val saving = "저축"
    override val transactionType = "거래 유형"

    // ===== Categories =====
    override val category = "카테고리"
    override val categoryManagement = "카테고리 관리"
    override val addIncomeCategory = "수입 카테고리 추가"
    override val addExpenseCategory = "지출 카테고리 추가"
    override val addCategory = "카테고리 추가"
    override val deleteCategory = "카테고리 삭제"
    override val editCategory = "카테고리 수정"
    override val incomeCategories = "수입 카테고리"
    override val expenseCategories = "지출 카테고리"
    override val categoryName = "카테고리 이름"
    override val selectCategory = "카테고리 선택"
    override val noCategorySelected = "선택된 카테고리 없음"
    override val uncategorized = "미분류"
    override val categoryColor = "카테고리 색상"
    override val categoryIcon = "카테고리 아이콘"
    override val defaultCategories = "기본 카테고리"
    override val customCategories = "사용자 정의 카테고리"
    override val cannotDeleteDefaultCategory = "기본 카테고리는 삭제할 수 없습니다"
    override val categoryInUseCannotDelete = "사용 중인 카테고리는 삭제할 수 없습니다"
    override val deleteCategoryConfirm = "이 카테고리를 삭제하시겠습니까?"

    // Default category names
    override val categorySalary = "급여"
    override val categoryBonus = "보너스"
    override val categoryInvestment = "투자"
    override val categoryAllowance = "용돈"
    override val categoryOtherIncome = "기타 수입"
    override val categoryFood = "식비"
    override val categoryTransport = "교통"
    override val categoryShopping = "쇼핑"
    override val categoryEntertainment = "문화/여가"
    override val categoryHealth = "의료/건강"
    override val categoryEducation = "교육"
    override val categoryHousing = "주거"
    override val categoryTelecom = "통신"
    override val categoryOtherExpense = "기타 지출"

    // ===== Payday Setup =====
    override val paydaySetup = "월급날 설정"
    override val paydaySetupTitle = "월급날을 설정해주세요"
    override val paydaySetupSubtitle = "월급 기간별로 지출을 관리할 수 있어요"
    override val paydaySetupDescription = "월급 기간별로 지출을 관리할 수 있어요"
    override val selectPaydayPrompt = "월급날을 선택해주세요"
    override val paydayOnWeekendHoliday = "월급날이 주말/공휴일인 경우"
    override val payBeforeWeekday = "이전 평일에 지급"
    override val payAfterWeekday = "이후 평일에 지급"
    override val setupComplete = "설정 완료"
    override val selectPayday = "월급날 선택"
    override val paydayChange = "월급날 변경"
    override val currentPayday = "현재 월급날"
    override val paydayAdjustment = "주말/공휴일 조정"
    override val beforeWeekend = "주말 이전에 지급"
    override val afterWeekend = "주말 이후에 지급"
    override val beforeWeekendDesc = "주말/공휴일이면 직전 영업일에 지급"
    override val afterWeekendDesc = "주말/공휴일이면 다음 영업일에 지급"
    override val monthlySalary = "월급"
    override val enterSalary = "월급을 입력하세요"
    override val salaryOptional = "선택사항"
    override val confirmPayday = "설정 완료"
    override val paydayChangeConfirm = "월급날을 변경하시겠습니까?"
    override val paydayChangeDesc = "월급날 설정 화면으로 이동합니다."
    override val goToPaydaySettings = "변경하기"
    override val welcomeMessage = "환영합니다!"
    override val welcomeSubMessage = "월급 관리를 시작해보세요"
    override fun paydayDisplay(day: Int) = "${day}일"

    // ===== Calendar Screen =====
    override val payPeriodSummary = "급여 기간 요약"
    override val remainingBudget = "남은 예산"
    override val totalIncome = "총 수입"
    override val totalExpense = "총 지출"
    override val balance = "잔액"
    override val dailyAverage = "일 평균"
    override val remainingDays = "남은 일수"
    override val noTransactions = "거래 내역이 없습니다"
    override val addFirstTransaction = "첫 번째 거래를 추가해보세요"
    override val viewTransactions = "거래 내역 보기"
    override val tapToAddTransaction = "탭하여 거래 추가"
    override fun remainingDaysCount(days: Int) = "${days}일 남음"
    override fun daysRemaining(days: Int) = "${days}일"
    override fun dailyBudgetRecommend(amount: String) = "하루 ${amount}원 사용 권장"
    override val budgetExceeded = "예산 초과"
    override val withinBudget = "예산 이내"
    override val showPayPeriod = "급여 기간 표시"
    override val hidePayPeriod = "급여 기간 숨기기"
    override val viewDetails = "상세 보기"
    override val payPeriodStart = "급여 기간 시작"
    override val payPeriodEnd = "급여 기간 종료"
    override fun payPeriodRange(startMonth: Int, startDay: Int, endMonth: Int, endDay: Int) =
        "${startMonth}월 ${startDay}일 ~ ${endMonth}월 ${endDay}일"
    override val incomeExpenseRatio = "수입/지출 비율"
    override val spendingPace = "지출 속도"
    override val onTrack = "적정 수준"
    override val overSpending = "초과 지출"
    override val underSpending = "절약 중"
    override val weekdaysShort = listOf("일", "월", "화", "수", "목", "금", "토")
    override val selectDateToMove = "이동할 날짜를 선택하세요"
    override val selectDateToViewMemo = "날짜를 선택해서 메모 보기"
    override val tapCalendarToViewMemo = "캘린더에서 날짜를 클릭하여 해당 날짜의 메모를 확인하세요"
    override val cardPaymentHistory = "카드 결제 내역"
    override val parsingPermission = "파싱권한"
    override val pushPermission = "푸시권한"
    override val yearLabel = "년도"
    override val monthLabel = "월"
    override fun yearDisplay(year: Int) = "${year}년"
    override fun monthDisplayShort(month: Int) = "${month}월"
    override val previousYear = "이전 년도"
    override val nextYear = "다음 년도"
    override val previousMonthLabel = "이전 월"
    override val nextMonthLabel = "다음 월"
    override fun dateTransactionHeader(month: Int, day: Int) = "${month}월 ${day}일 거래 내역"
    override val noTransactionsOnDate = "이 날짜에 거래 내역이 없습니다"

    // ===== Add/Edit Transaction =====
    override val addTransaction = "거래 추가"
    override val editTransaction = "거래 수정"
    override val transactionDate = "거래 날짜"
    override val transactionAmount = "거래 금액"
    override val transactionMemo = "메모"
    override val enterAmount = "금액을 입력하세요"
    override val enterMemo = "메모를 입력하세요"
    override val selectDate = "날짜 선택"
    override val selectPaymentMethod = "결제 수단 선택"
    override val cash = "현금"
    override val card = "카드"
    override val bankTransfer = "계좌이체"
    override val giftCard = "상품권"
    override val paymentMethod = "결제 수단"
    override val transactionSaved = "거래가 저장되었습니다"
    override val transactionDeleted = "거래가 삭제되었습니다"
    override val deleteTransactionConfirm = "이 거래를 삭제하시겠습니까?"
    override val amountRequired = "금액을 입력해주세요"
    override val invalidAmount = "올바른 금액을 입력해주세요"
    override val memo = "메모"
    override val noMemo = "메모 없음"
    override val transactionDetails = "거래 상세"
    override val duplicateTransaction = "중복 거래"
    override val similarTransactionExists = "비슷한 거래가 이미 존재합니다"

    // ===== Date Detail Screen =====
    override val dateDetail = "날짜 상세"
    override val transactionsForDay = "당일 거래 내역"
    override fun transactionCount(count: Int) = "${count}건"
    override val noTransactionsForDay = "이 날의 거래 내역이 없습니다"
    override val dailySummary = "일일 요약"
    override val totalForDay = "당일 합계"
    override val incomeForDay = "당일 수입"
    override val expenseForDay = "당일 지출"
    override val deleteTransactionTitle = "거래 삭제"
    override val cannotDeleteTransaction = "거래 삭제 불가"
    override val recurringShort = "반복"
    override val saveAsRecurring = "반복거래로 저장"
    override fun transactionListHeader(count: Int) = "거래 내역 (${count}건)"

    // ===== Statistics Screen =====
    override val statistics = "통계"
    override val statisticsTitle = "지출 분석"
    override val monthlyStatistics = "월별 통계"
    override val categoryStatistics = "카테고리별 통계"
    override val paymentMethodStatistics = "결제 수단별 통계"
    override val spendingTrend = "지출 추이"
    override val incomeVsExpense = "수입 vs 지출"
    override val topCategories = "상위 카테고리"
    override val topExpenseCategories = "지출 상위 카테고리"
    override val topIncomeCategories = "수입 상위 카테고리"
    override val noDataForPeriod = "해당 기간의 데이터가 없습니다"
    override val averageDaily = "일 평균"
    override val averageMonthly = "월 평균"
    override val highestSpendingDay = "최고 지출일"
    override val lowestSpendingDay = "최저 지출일"
    override val totalTransactions = "총 거래 수"
    override val chartView = "차트 보기"
    override val listView = "목록 보기"
    override val pieChart = "파이 차트"
    override val barChart = "막대 차트"
    override val lineChart = "선 차트"
    override fun categoryPercentage(category: String, percentage: Int) = "$category ${percentage}%"

    // ===== Budget Settings =====
    override val budgetSettings = "예산 설정"
    override val setBudget = "예산 설정"
    override val editBudget = "예산 수정"
    override val deleteBudget = "예산 삭제"
    override val monthlyBudget = "월 예산"
    override val categoryBudget = "카테고리 예산"
    override val budgetAmount = "예산 금액"
    override val enterBudgetAmount = "예산 금액을 입력하세요"
    override val budgetRemaining = "남은 예산"
    override val budgetUsed = "사용한 예산"
    override val budgetExceededWarning = "예산을 초과했습니다!"
    override val noBudgetSet = "설정된 예산이 없습니다"
    override val budgetSaved = "예산이 저장되었습니다"
    override val budgetDeleted = "예산이 삭제되었습니다"
    override val deleteBudgetConfirm = "이 예산을 삭제하시겠습니까?"
    override val viewBudgetProgress = "예산 진행 상황 보기"
    override fun budgetProgress(used: String, total: String) = "${used}원 / ${total}원"
    override fun budgetRemainingAmount(amount: String) = "${amount}원 남음"
    override fun budgetExceededAmount(amount: String) = "${amount}원 초과"
    override val budgetExceededNotification = "예산 초과 알림"
    override val totalBudget = "총 예산"
    override val usedAmount = "사용 금액"
    override val remainingAmount = "남은 금액"
    override val budgetUtilization = "예산 사용률"

    // ===== Card Management =====
    override val cardManagement = "카드 관리"
    override val addCard = "카드 추가"
    override val editCard = "카드 수정"
    override val deleteCard = "카드 삭제"
    override val cardName = "카드 이름"
    override val cardType = "카드 유형"
    override val creditCard = "신용카드"
    override val debitCard = "체크카드"
    override val prepaidCard = "선불카드"
    override val balanceCard = "잔액권"
    override val cardBalance = "카드 잔액"
    override val enterCardName = "카드 이름을 입력하세요"
    override val enterCardBalance = "잔액을 입력하세요"
    override val cardList = "카드 목록"
    override val noCards = "등록된 카드가 없습니다"
    override val addFirstCard = "첫 번째 카드를 추가해보세요"
    override val cardSaved = "카드가 저장되었습니다"
    override val cardDeleted = "카드가 삭제되었습니다"
    override val deleteCardConfirm = "이 카드를 삭제하시겠습니까?"
    override val cardDetails = "카드 상세"
    override val lastUsed = "마지막 사용"
    override val totalSpent = "총 사용 금액"
    override val balanceCardManagement = "잔액권 관리"
    override val giftCardManagement = "상품권 관리"
    override val addBalanceCard = "잔액권 추가"
    override val addGiftCard = "상품권 추가"
    override val editBalanceCard = "잔액권 수정"
    override val editGiftCard = "상품권 수정"
    override val initialBalance = "초기 잔액"
    override val currentBalance = "현재 잔액"
    override val usedBalance = "사용 잔액"
    override val expirationDate = "유효기간"
    override val noExpirationDate = "유효기간 없음"
    override val setExpirationDate = "유효기간 설정"
    override val cardExpired = "만료됨"
    override val cardExpiringSoon = "곧 만료"
    override val activeCards = "활성 카드"
    override val inactiveCards = "비활성 카드"
    override val markAsUsed = "사용 완료 처리"
    override val activateCard = "카드 활성화"

    // ===== Recurring Transactions =====
    override val recurringTransactions = "반복 거래"
    override val addRecurringTransaction = "반복 거래 추가"
    override val editRecurringTransaction = "반복 거래 수정"
    override val deleteRecurringTransaction = "반복 거래 삭제"
    override val recurringTransactionName = "거래 이름"
    override val recurrencePattern = "반복 주기"
    override val daily = "매일"
    override val weekly = "매주"
    override val monthly = "매월"
    override val yearly = "매년"
    override val everyDay = "매일"
    override val everyWeek = "매주"
    override val everyMonth = "매월"
    override val everyYear = "매년"
    override val selectRecurrenceDay = "반복 일자 선택"
    override val recurringAmount = "반복 금액"
    override val startDate = "시작일"
    override val endDate = "종료일"
    override val noEndDate = "종료일 없음"
    override val nextOccurrence = "다음 실행일"
    override val lastExecuted = "마지막 실행"
    override val neverExecuted = "실행된 적 없음"
    override val recurringTransactionSaved = "반복 거래가 저장되었습니다"
    override val recurringTransactionDeleted = "반복 거래가 삭제되었습니다"
    override val deleteRecurringTransactionConfirm = "이 반복 거래를 삭제하시겠습니까?"
    override val recurringTransactionPaused = "반복 거래가 일시정지되었습니다"
    override val recurringTransactionResumed = "반복 거래가 재개되었습니다"
    override val pauseRecurring = "일시정지"
    override val resumeRecurring = "재개"
    override val executeNow = "지금 실행"
    override val skipNext = "다음 건너뛰기"
    override val noRecurringTransactions = "반복 거래가 없습니다"
    override val addFirstRecurringTransaction = "첫 번째 반복 거래를 추가해보세요"
    override val recurringTransactionDetails = "반복 거래 상세"
    override val autoAdd = "자동 추가"
    override val manualConfirm = "수동 확인"
    override val autoAddDesc = "해당 날짜에 자동으로 거래가 추가됩니다"
    override val manualConfirmDesc = "알림을 통해 확인 후 거래가 추가됩니다"
    override fun recurringDayOfMonth(day: Int) = "매월 ${day}일"
    override fun recurringDayOfWeek(weekday: String) = "매주 $weekday"
    override val todaysRecurringTransactions = "오늘의 반복 거래"
    override val pendingRecurringTransactions = "대기 중인 반복 거래"

    // ===== Parsed Transactions (SMS/Notification) =====
    override val parsedTransactions = "파싱된 거래"
    override val cardNotificationParsing = "카드 알림 파싱"
    override val parsedTransactionsList = "파싱된 거래 목록"
    override val addToParsed = "거래로 추가"
    override val ignoreParsed = "무시"
    override val allParsed = "전체"
    override val parsedFromNotification = "알림에서 파싱됨"
    override val noParsedTransactions = "파싱된 거래가 없습니다"
    override val parsedTransactionAdded = "거래가 추가되었습니다"
    override val parsedTransactionIgnored = "거래가 무시되었습니다"
    override val deleteAllParsed = "전체 삭제"
    override val deleteAllParsedConfirm = "파싱된 모든 거래를 삭제하시겠습니까?"
    override val cardNotificationDetection = "카드 알림 감지"
    override val cardNotificationDetectionDesc = "다른 앱의 카드 알림을 파싱"
    override val appNotification = "앱 알림"
    override val appNotificationDesc = "앱에서 알림 받기"

    // ===== Theme Settings =====
    override val themeSettings = "테마 설정"
    override val theme = "테마"
    override val lightTheme = "라이트 모드"
    override val darkTheme = "다크 모드"
    override val systemTheme = "시스템 설정"
    override val themeLight = "라이트"
    override val themeDark = "다크"
    override val themeSystem = "시스템"

    // ===== Language Settings =====
    override val languageSettings = "언어 설정"
    override val language = "언어"
    override val korean = "한국어"
    override val english = "English"
    override val languageChangeRestart = "언어 변경을 적용하려면 앱을 다시 시작해야 합니다"
    override val selectLanguage = "언어 선택"

    // ===== Data Management =====
    override val dataManagement = "데이터 관리"
    override val exportData = "데이터 내보내기"
    override val importData = "데이터 가져오기"
    override val exportToJson = "JSON으로 내보내기"
    override val importFromJson = "JSON에서 가져오기"
    override val exportDataDesc = "전체 데이터를 JSON 파일로 저장"
    override val importDataDesc = "JSON 파일에서 데이터 복원"
    override val exportSuccess = "데이터를 성공적으로 내보냈습니다"
    override val exportFailed = "내보내기 실패"
    override val importSuccess = "데이터를 성공적으로 가져왔습니다"
    override val importFailed = "가져오기 실패"
    override val importConfirm = "데이터 가져오기"
    override val importConfirmDesc = "JSON 파일에 포함된 데이터를 가져옵니다.\n기존 데이터는 삭제됩니다.\n\n계속하시겠습니까?"
    override val importWarning = "경고"
    override val existingDataWillBeDeleted = "기존 데이터는 삭제됩니다"
    override val fileLoadFailed = "파일 불러오기 실패"
    override fun importResult(success: Int, failed: Int) = "데이터 가져오기 완료\n성공: $success, 실패: $failed"
    override val backupData = "데이터 백업"
    override val restoreData = "데이터 복원"

    // ===== Calculator =====
    override val calculator = "계산기"
    override val calculate = "계산"
    override val clear = "지우기"
    override val clearAll = "전체 지우기"
    override val equals = "="
    override val useResult = "결과 사용"
    override val calculatorResult = "계산 결과"

    // ===== Tip Donation =====
    override val tipDonation = "개발자 후원"
    override val tipDonationTitle = "개발자 후원"
    override val tipDonationDesc = "앱 개발에 도움을 주세요"
    override val supportDeveloper = "개발자 지원"
    override val smallTip = "커피 한 잔"
    override val mediumTip = "점심 식사"
    override val largeTip = "저녁 식사"
    override val thankYouForTip = "후원해 주셔서 감사합니다!"
    override val tipPurchaseFailed = "구매에 실패했습니다"
    override val tipAlreadyPurchased = "이미 구매하셨습니다"

    // ===== Ad Removal =====
    override val adRemoval = "광고 제거"
    override val removeAds = "광고 제거"
    override val adRemovalDesc = "광고 없이 앱을 사용하세요"
    override val adRemovalBenefit = "광고 제거 혜택"
    override val adFreeExperience = "광고 없는 쾌적한 사용 경험"
    override val purchaseAdRemoval = "광고 제거 구매"
    override val adRemovalActive = "광고 제거 활성화됨"
    override val adRemovalExpired = "광고 제거가 만료되었습니다"
    override fun adRemovalExpiresIn(days: Int) = "${days}일 후 만료"
    override val restorePurchase = "구매 복원"
    override val purchaseFailed = "구매 실패"
    override val purchaseSuccess = "구매 완료"

    // ===== Coupon =====
    override val coupon = "쿠폰"
    override val enterCoupon = "쿠폰 입력"
    override val couponCode = "쿠폰 코드"
    override val applyCoupon = "쿠폰 적용"
    override val invalidCoupon = "유효하지 않은 쿠폰입니다"
    override val couponAlreadyUsed = "이미 사용한 쿠폰입니다"
    override val couponApplied = "쿠폰이 적용되었습니다"
    override val couponExpired = "만료된 쿠폰입니다"
    override val couponNotFound = "쿠폰을 찾을 수 없습니다"
    override val enterCouponCode = "쿠폰 코드를 입력하세요"

    // ===== Monthly Comparison =====
    override val monthlyComparison = "월별 비교"
    override val compareMonths = "월 비교"
    override val previousMonth = "전월"
    override val currentMonth = "당월"
    override val difference = "차이"
    override val increased = "증가"
    override val decreased = "감소"
    override val noChange = "변동 없음"
    override fun comparedToLastMonth(amount: String) = "전월 대비 $amount"
    override fun increasePercentage(percentage: Int) = "${percentage}% 증가"
    override fun decreasePercentage(percentage: Int) = "${percentage}% 감소"
    override val previousPayPeriod = "직전 급여 기간"
    override val currentPayPeriod = "현재 급여 기간"
    override val payPeriodComparison = "급여 기간 비교"
    override val newPayPeriodStarted = "새로운 급여일이 시작됐어요! 지난 달과 비교해보세요"
    override val compareWithPreviousPeriod = "직전 기간과 비교해보세요"

    // ===== Tutorial =====
    override val tutorialWelcome = "환영합니다!"
    override val tutorialCalendar = "캘린더에서 날짜별 거래를 확인하세요"
    override val tutorialAddTransaction = "여기를 눌러 거래를 추가하세요"
    override val tutorialStatistics = "통계에서 지출 패턴을 분석하세요"
    override val tutorialBudget = "예산을 설정하고 지출을 관리하세요"
    override val tutorialSkip = "건너뛰기"
    override val tutorialNext = "다음"
    override val tutorialFinish = "완료"
    override val tutorialDontShowAgain = "다시 보지 않기"
    override val tapHereToAdd = "여기를 눌러 추가"
    override val swipeToNavigate = "스와이프로 이동"
    override val longPressForOptions = "길게 눌러 옵션 보기"

    // ===== Permissions =====
    override val permissionRequired = "권한 필요"
    override val notificationListenerPermission = "알림 리스너 권한"
    override val notificationListenerPermissionDesc = "카드 알림을 감지하려면 알림 리스너 권한이 필요합니다.\n\n설정 화면으로 이동하시겠습니까?"
    override val postNotificationPermission = "알림 전송 권한"
    override val postNotificationPermissionDesc = "앱 알림을 표시하려면 알림 전송 권한이 필요합니다.\n\n설정 화면으로 이동하시겠습니까?"
    override val goToSettings = "설정하기"
    override val permissionDenied = "권한이 거부되었습니다"
    override val permissionGranted = "권한이 허용되었습니다"

    // ===== Errors & Validation =====
    override val networkError = "네트워크 오류"
    override val unknownError = "알 수 없는 오류"
    override val tryAgain = "다시 시도"
    override val dataLoadFailed = "데이터 로딩 실패"
    override val dataSaveFailed = "데이터 저장 실패"
    override val requiredField = "필수 입력 항목입니다"
    override val invalidInput = "올바르지 않은 입력입니다"
    override val valueTooLarge = "값이 너무 큽니다"
    override val valueTooSmall = "값이 너무 작습니다"
    override val pleaseEnterValidAmount = "올바른 금액을 입력해주세요"
    override val pleaseSelectCategory = "카테고리를 선택해주세요"
    override val connectionFailed = "연결 실패"
    override val timeout = "시간 초과"

    // ===== Drawer Menu =====
    override val pushNotifications = "푸시 알림"
    override val aboutApp = "앱 정보"
    override val version = "버전"
    override val contactSupport = "문의하기"
    override val rateApp = "앱 평가"
    override val privacyPolicy = "개인정보 처리방침"
    override val termsOfService = "이용약관"
    override val appExit = "앱 종료"
    override val exitConfirm = "종료"
    override val exitConfirmMessage = "앱을 종료하시겠습니까?"
    override val hideMoneyAmounts = "금액 숨기기"
    override val showMoneyAmounts = "금액 보이기"
    override val moneyVisibility = "금액 표시"
    override fun addIncomeExpenseCategory(type: String) = "$type 카테고리 추가 및 삭제"

    // ===== Snackbar & Toast Messages =====
    override val changesSaved = "변경사항이 저장되었습니다"
    override val changesDiscarded = "변경사항이 취소되었습니다"
    override val operationSuccess = "작업이 완료되었습니다"
    override val operationFailed = "작업에 실패했습니다"
    override val copiedToClipboard = "클립보드에 복사되었습니다"
    override val undoAction = "실행 취소"
    override val actionCancelled = "작업이 취소되었습니다"

    // ===== Empty States =====
    override val noDataYet = "아직 데이터가 없습니다"
    override val startByAdding = "추가하여 시작하세요"
    override val nothingToShow = "표시할 내용이 없습니다"
    override val emptyCategory = "카테고리가 비어있습니다"
    override val emptyCardList = "등록된 카드가 없습니다"
    override val emptyTransactionList = "거래 내역이 없습니다"
    override val emptyBudgetList = "설정된 예산이 없습니다"
    override val emptyRecurringList = "반복 거래가 없습니다"
    override val emptyStatistics = "통계 데이터가 없습니다"

    // ===== Accessibility =====
    override val closeDialog = "다이얼로그 닫기"
    override val openMenu = "메뉴 열기"
    override val closeMenu = "메뉴 닫기"
    override val goBack = "뒤로 가기"
    override val moreOptions = "더 보기"
    override val refresh = "새로고침"
    override val scrollUp = "위로 스크롤"
    override val scrollDown = "아래로 스크롤"
    override val expandSection = "섹션 펼치기"
    override val collapseSection = "섹션 접기"

    // ===== Statistics (additional) =====
    override val incomeAnalysis = "수입 분석"
    override val expenseAnalysis = "지출 분석"
    override val investmentActivityAnalysis = "투자 활동 분석"
    override val savingActivitySummary = "저축 활동 요약"
    override val savingCategories = "저축 카테고리"
    override val addSavingCategory = "저축 카테고리 추가"
    override val investmentActivitySummary = "투자 활동 요약"
    override val investment = "투자"
    override val stopLoss = "손절"
    override val profitTaking = "익절"
    override val dividend = "배당금"
    override val paymentMethodAnalysis = "결제 수단별 분석"
    override val noTransactionsForPeriod = "이 기간에 거래 내역이 없습니다"
    override val differenceAmount = "차액"
    override val charge = "충전"
    override val usage = "사용"
    override val purchase = "구매"
    override val settlementIncome = "정산수입"
    override val actualUsage = "실제 사용"
    override val other = "기타"

    // ===== Budget (additional) =====
    override val budgetManagement = "예산 관리"
    override val usageStatus = "사용 현황"
    override val overallProgress = "전체 진행도"
    override val spendingPlan = "지출 계획"
    override val plannedTotal = "계획 합계:"
    override val salaryLabel = "급여:"
    override val budgetLabel = "예산:"
    override val usedLabel = "사용:"
    override val remainingLabel = "남음:"
    override val exceededLabel = "초과:"
    override val noBudgetCategoriesMessage = "예산이 설정된 카테고리가 없습니다.\n\"예산 설정\" 탭에서 카테고리를 추가해주세요."
    override val addCategoryLabel = "+ 카테고리 추가"
    override val allocatedAmount = "배분 금액"
    override val enterAmountPlaceholder = "금액을 입력하세요"
    override val selectCategoriesMultiple = "카테고리 선택 (복수 선택 가능)"
    override val groupNameInput = "그룹명 입력"
    override val groupNameLabel = "그룹명"
    override val memoOptional = "메모 (선택사항)"
    override val noCategoriesAvailable = "추가할 수 있는 카테고리가 없습니다."
    override val includedCategories = "포함된 카테고리:"
    override val categorySpending = "카테고리별 지출:"
    override val totalLabel = "총:"
    override val editSalary = "급여 수정"
    override val setSalary = "급여를 설정하세요"
    override val addCategoryBudget = "카테고리 예산 추가"
    override fun editBudgetTitle(emoji: String, name: String) = "$emoji $name 예산 수정"

    // ===== Add Transaction (additional) =====
    override val savingTransaction = "저장 중..."
    override val dateLabel = "날짜"
    override val merchantLabel = "사용처"
    override val incomeType = "수입 유형"
    override val newBalanceCard = "새 잔액권 추가"
    override val chargeExistingBalanceCard = "기존 잔액권 충전"
    override val balanceCardNameHint = "잔액권 이름 (예: 편의점 상품권)"
    override val giftCardNameHint = "상품권 이름 (예: 신세계 상품권)"
    override val selectBalanceCardToCharge = "충전할 잔액권 선택"
    override val selectBalanceCardLabel = "잔액권 선택"
    override val purchaseAmountLabel = "실제 구매금액 (선택)"
    override val purchaseAmountHint = "할인 구매 시 실제 지불한 금액"
    override val selectGiftCardLabel = "상품권 선택"
    override val dutchPaySettlement = "더치페이/정산"
    override val settlementAmountLabel = "정산받을 금액"
    override val settlementDescription = "결제 금액에서 정산받을 금액을 뺀 나머지가 실제 내 부담액으로 표시됩니다"
    override fun balanceCardFullUsage(amount: Int, remaining: Int) = "잔액권 ${amount}원 사용, 잔액 ${remaining}원"
    override fun balanceCardPartialUsage(cardAmount: Int, cashAmount: Int) = "잔액권 ${cardAmount}원 + 현금 ${cashAmount}원 지출"
    override fun giftCardFullUsage(amount: Int) = "상품권 ${amount}원 전액 사용"
    override fun giftCardRefundUsage(amount: Int, refund: Int) = "상품권 ${amount}원 사용, ${refund}원 현금 환급"
    override fun giftCardPartialUsage(cardAmount: Int, cashAmount: Int) = "상품권 ${cardAmount}원 + 현금 ${cashAmount}원 지출"

    // ===== Calculator (additional) =====
    override val periodCalculator = "기간별 계산기"
    override val periodSetting = "기간 설정"
    override val editPeriod = "기간 수정"
    override val totalAmount = "총액"
    override val transactionCountLabel = "거래 건수"
    override val averageAmount = "평균 금액"
    override val selectStartDate = "시작일을 선택해주세요"
    override val selectEndDate = "종료일을 선택해주세요"
    override val selectionComplete = "선택 완료"
    override val transactionDetail = "거래 상세"

    // ===== Theme (additional) =====
    override val systemThemeDesc = "기기의 테마 설정을 따릅니다"

    // ===== Coupon (additional) =====
    override val couponCodeInput = "쿠폰 코드 입력"
    override val couponDesc = "쿠폰 코드를 입력하시면 3일간 광고 없이 사용하실 수 있습니다."
    override val applyingCoupon = "적용 중..."
    override val applyCouponButton = "쿠폰 적용하기"
    override val couponApplyComplete = "쿠폰 적용 완료!"
    override val couponSuccessMessage = "쿠폰이 성공적으로 적용되었습니다.\n3일간 광고 없이 사용하실 수 있습니다.\n\n앱을 재시작하면 적용됩니다."

    // ===== Ad Removal (additional) =====
    override val useWithoutAds = "광고 없이 사용하기"
    override val adRemovalLongDesc = "광고 없이 쾌적하게 앱을 사용하세요!\n기간을 선택하시면 해당 기간 동안 광고가 표시되지 않습니다."
    override val oneDayPass = "1일 이용권"
    override val threeDayPass = "3일 이용권"
    override val sevenDayPass = "7일 이용권"
    override val thirtyDayPass = "30일 이용권"
    override val processingPayment = "결제 처리 중..."
    override fun payAmountButton(amount: String) = "₩${amount} 결제하기"
    override val selectPeriod = "기간을 선택해주세요"
    override val purchaseComplete = "구매 완료!"
    override val adRemovalCompleteMessage = "광고 제거가 완료되었습니다.\n쾌적하게 앱을 사용하세요!"
    override val paymentFailedTitle = "결제 실패"

    // ===== Tip Donation (additional) =====
    override val tipDonationScreenTitle = "팁주기"
    override val supportDeveloperTitle = "개발자 응원하기"
    override val tipDonationLongDesc = "앱이 도움이 되셨나요?\n개발자에게 커피 한 잔 사주세요!"
    override val buyCoffee = "커피 사주기"
    override val buyLunch = "점심 사주기"
    override val buyDinner = "저녁 사주기"
    override val selectAmountPrompt = "금액을 선택해주세요"
    override val thankYouTitle = "감사합니다!"
    override val thankYouMessage = "개발자를 응원해주셔서 감사합니다.\n더 좋은 앱으로 보답하겠습니다!"

    // ===== Monthly Comparison (additional) =====
    override val categoryComparison = "카테고리별 비교"
    override val noComparisonData = "비교할 데이터가 없습니다"
    override val totalExpenseComparison = "📊 총 지출 비교"
    override val totalSavingComparison = "🐷 총 저축 비교"
    override val totalInvestmentComparison = "💹 총 투자 비교"
    override val previous = "이전"
    override val current = "현재"
    override val increasedArrow = "증가 ↑"
    override val savingsArrow = "절약 ↓"
    override val same = "동일"

    // ===== Parsed Transactions (additional) =====
    override val parsedTransactionDesc = "알림에서 파싱된 거래 내역입니다. 항목을 클릭하여 거래를 추가하세요."
    override fun errorWithMessage(message: String) = "오류: $message"
    override val cardNotificationAutoDisplay = "카드 결제 알림이 오면 자동으로 표시됩니다"
    override val notificationOn = "🔔 알림"
    override val notificationOff = "🔕 알림"

    // ===== Category Management (additional) =====
    override val emojiLabel = "이모지"
    override val continueAction = "계속"
    override fun deleteCategoryConfirmMessage(emoji: String, name: String) = "$emoji $name 카테고리를 정말 삭제하시겠습니까?"
    override val deleteCategoryTransactionWarning = "해당 카테고리로 등록된 기존 거래 내역은 삭제되지 않습니다."

    // ===== Card Management (additional) =====
    override val balanceGiftCardManagement = "잔액권/상품권 관리"
    override val activeTab = "사용중"
    override val completedTab = "사용완료"
    override val noActiveCards = "사용중인 카드가 없습니다"
    override val noCompletedCards = "사용완료된 카드가 없습니다"
    override fun balanceDisplay(amount: String) = "잔액: ${amount}원"
    override val transactionHistory = "거래 내역"
    override val noTransactionHistory = "거래 내역이 없습니다"
    override fun incomeAmountDisplay(amount: String) = "+${amount}원"
    override fun expenseAmountDisplay(amount: String) = "-${amount}원"

    // ===== Recurring Transaction (additional) =====
    override val recurringTransactionManagement = "반복 거래 관리"
    override val todayItems = "오늘 실행할 항목"
    override val noRegisteredRecurringTransactions = "등록된 반복 거래가 없습니다"
    override val recurringAutoExecute = "반복 거래 자동 실행"
    override val recurringAutoExecuteDescription = "오늘 예정된 반복 거래를 자동으로 등록합니다"
    override fun paymentMethodDisplay(method: String) = "결제수단: $method"
    override val cashCheckCard = "현금/체크카드"
    override val recurringPatternLabel = "반복 패턴"
    override val whichDayOfMonth = "매달 몇 일?"
    override val whichDayOfWeek = "매주 무슨 요일?"
    override val weekendHandling = "주말 처리"
    override val applyAsIs = "그대로 적용"
    override val moveToPreviousWeekday = "이전 평일로"
    override val moveToNextWeekday = "다음 평일로"
    override val noCategoriesRegistered = "등록된 카테고리가 없습니다"
    override val memoOptionalShort = "메모 (선택)"

    // ===== Custom Payment Method Management =====
    override val paymentMethodManagement = "결제수단 관리"
    override val addPaymentMethod = "결제수단 추가"
    override val editPaymentMethod = "결제수단 수정"
    override val deletePaymentMethod = "결제수단 삭제"
    override val paymentMethodName = "결제수단 이름"
    override val paymentMethodManagementDesc = "카드별 지출을 구분하여 관리합니다"
    override val defaultPaymentMethods = "기본 결제수단"
    override val customPaymentMethods = "등록된 카드"
    override val unspecifiedCard = "미지정"
    override fun deletePaymentMethodConfirmMessage(name: String) = "$name 결제수단을 정말 삭제하시겠습니까?"
    override fun totalPaymentMethodCount(defaultCount: Int, customCount: Int) = "총 ${defaultCount + customCount}개의 결제수단"
    override fun defaultPaymentMethodCount(count: Int) = "${count}개"
    override fun customPaymentMethodCount(count: Int) = "${count}개"
    override val selectCard = "카드 선택"
    override val defaultCard = "기본"
    override val setAsDefaultCard = "기본 카드로 설정"
    override val cardBreakdown = "카드별 내역"
    override val transactionTools = "거래 도구"

    // ===== Transaction Search =====
    override val transactionSearch = "거래 검색"
    override val searchHint = "사용처 또는 메모로 검색"
    override val noSearchResults = "검색 결과가 없습니다"
    override fun searchResultCount(count: Int) = "${count}건"

    // ===== Search Filter =====
    override val filter = "필터"
    override val filterReset = "초기화"
    override val filterTransactionType = "거래 유형"
    override val filterCategory = "카테고리"
    override val filterAmountRange = "금액 범위"
    override val filterDateRange = "날짜 범위"
    override val filterMinAmount = "최소"
    override val filterMaxAmount = "최대"
    override val filterStartDate = "시작일"
    override val filterEndDate = "종료일"
    override val filterAll = "전체"
}
